name: laravel code check

on:
  pull_request:
    branches:
      - '**'

jobs:
  larastan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Larastan
        run: vendor/bin/phpstan analyse

  pint:
      runs-on: ubuntu-24.04

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'
            extensions: mbstring, xml

        - name: Install dependencies
          run: composer install --no-interaction --prefer-dist

        - name: Run Laravel Pint Check
          run: vendor/bin/pint --test
